### ISSUE TITLE
Unable to Set Timeznoe

### ISSUE THREAD

**Issue by Disgruntled-Duck** [brav0charlie/docker-dnsmasq#2]
Hey there, 

Hopefully this is a simple issue but I cannot get the timezone file to work. I tried installing the tzdata and copied the timezone file to persistent storage, I tried a symbolic link from my host machine, and I tried make an env variable for the TZ but can't seem to get it to accept it. When I installed the tzdata it properly changed the timezone but once I recreated it went back to UTC even though the timezone file was still in /etc/localtime

Were you able to get this to work? How did link / copy the tz file and have it stick?

**Comment by brav0charlie** [comment]
In the docker-compose.yml file, try adding the following under volumes, just below the first entry (the line for /etc/localtime):

`- /etc/timezone:/etc/timezone:ro`

So instead of:

```    
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - './config:/etc/dnsmasq.d'
      - './log:/var/log/dnsmasq'
```

You would have:

```
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
      - './config:/etc/dnsmasq.d'
      - './log:/var/log/dnsmasq'
```

**Comment by Disgruntled-Duck** [comment]
I tried what you had above:

    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
      - './config:/etc/dnsmasq.d'
      - './log:/var/log/dnsmasq'
      
And I also tried using local persistent file storage but it did not work for me. Just wanted to confirm that this is what the files should like like in alpine:

/ # cat /etc/timezone 
America/Los_Angeles/ # 

/ # cat /etc/localtime 
TZif2H*ˉ#pa&t\؀Ðޥݩ޾߉iip~KIR^-)4GJQ',3qАo_O?/v( fe HG *) 
                                                       x
                                                         q(a'Q
A       0C      ΐ        

௠
 #j$5 %J& '*'))6 "S      54 v+ !"V
eGYe턠g';gfiiHjke lmvG noV) pq6: XX YZ [޵\ ]^d _y`Mޠab-cgwdmE G-Gӵ I
                                ros tOt v8vxx͠yz{f|~}H~^s*&
                                                        LMTPDTPSTPWTPPTTZif2^H*ˉ#pa&t\؀Ðޥݩ޾߉iip~KIR^-)4GJQ',3qАo_O?/v( fe HG *) 
                                                                                                                               x
                                                                                                                                 q(a'Q
A       0C      ΐ        

௠
 #j$5 %J& '*'))6 "S      54 v+ !"V
eGYe턠g';gfiiHjke lmvG noV) pq6: XX YZ [޵\ ]^d _y`Mޠab-cgwdmE G-Gӵ I
                                ros tOt v8vxx͠yz{f|~}H~^s*&
                                                        LMTPDTPSTPWTPPT
PST8PDT,M3.2.0,M11.1.0
/ # 

/ # date
Sat Aug 31 19:56:16 UTC 2024
/ # 

I wasn't sure if they were supposed to be directories or linked to the actual file but this is my compose when I used persistent storage:

     volumes:
      - /share/dnsmasq/etc/localtime:/etc/localtime:ro
      - /share/dnsmasq/etc/timezone:/etc/timezone:ro
      - /share/dnsmasq/config:/etc/dnsmasq.d
      - /share/dnsmasq/log:/var/log/dnsmasq

**Comment by brav0charlie** [comment]
In the code block at the end of your comment, it looks like you're mapping /etc/localtime and /etc/timezone in the container to /share/dnsmasq/etc/localtime (and timezone). Did you copy the /etc/localtime and /etc/timezone files from your host computer into that /share/dnsmasq/etc directory?

In docker compose, when defining static volume links, it's `/host/path/here:/container/path/here`.

Try using the the timezone & localtime lines exactly as I provided them, and if that fails, try also adding:

```
  environment:
    - "TZ=America/Los_Angeles"
```

to the docker-compose.yml. 

So for example: 
```
# file: docker-compose.yml
# description: This file provides a docker container running docker-dnsmasq.

networks:
  dnsmasq:
    name: 'dnsmasq'

services:
  dnsmasq:
    container_name: 'dnsmasq'
    image: 'ghcr.io/brav0charlie/docker-dnsmasq:latest'
    cap_add:
      - 'NET_ADMIN'
      # Adding NET_ADMIN capability is required for DHCP Server to function
    ports:
      - '53:53/udp'
      - '67:67/udp'
      - '68:68/udp'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
      - './config:/etc/dnsmasq.d'
      - './log:/var/log/dnsmasq'
    environment:
      - 'TZ=America/Los_Angeles'
    networks:
      - 'dnsmasq'
```
